export const CHANGE_NETWORK = 'CHANGE_NETWORK'
export const SET_WEATHER_NOW = 'SET_WEATHER_NOW'
export const SET_WEATHER_FUTURE = 'SET_WEATHER_FUTURE'
export const SET_LIFE_SUGGESTION = 'SET_LIFE_SUGGESTION'